version: "3"
services:
  ubuntu-texlive-ja:
    #image: korosuke613/ubuntu-texlive-ja
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/root/.gitconfig
    environment:
      SHELL: "/bin/bash"